title: Autonomie
description: Diese Fragen helfen dir, deine Autonomie besser einzuschätzen.
answers:
- option 1
- option 2
- option 3
categories:
- A: Autonomie
- B: Bezogenheit
- S: Sicherheit
chart:
- type: radar