title: Autonomie
description: Autonomie-Fragebogen von Dr. Langlotz
answers:
  - trifft nicht zu: 1
  - stimmt selten: 2
  - manchmal: 3
  - stimmt häufig: 4
  - stimmt fast immer: 5
categories:
  - A: gesunde Abgrenzung
  - B: gesunder Egoismus
  - C: gesunde Aggression
  - D: Überabgrenzung
  - E: Übergriffigkeit
  - F: Destruktive Aggression
chart:
  type: radar
  top: B
input:
  element: radiobox
  display: column 