title: Autonomie
description: Autonomie-Fragebogen von Dr. Langlotz
answers:
  - option 1: 1
  - option 2: 2
  - option 3: 3
categories:
  - A: Autonomie
  - B: Bezogenheit
  - S: Sicherheit
chart:
  - type: radar